name: 'Tag Commit'
description: 'Crea un tag Git en el commit actual'
author: 'cristiannorga'
inputs:
  tag-name:
    description: 'Nombre del tag a crear'
    required: true
    default: 'ci/manual-tag'
runs:
  using: 'node20'
  main: 'compiled/index.js'  # El archivo JS que será ejecutado
branding:
  icon: 'tag'
  color: 'purple'
